package random.string.generator;

import java.util.Random;

public class Main {
	
	private static int randomLength = 0;	// length of the random string...
	private static final int MAX_LENGTH = 99;		// maximum length of the random string...
	private static final char[] ALPHA_NUMERICS = new char[36];		// an array to hold 36 alphanumeric characters...
	
	private static final Random RANDOM = new Random();		// java.util.Random class to generate random numbers...
	
	public static void main(String[] args) {
		int i = 0;		// loop variable...
		
		StringBuilder randomStringBuilder = new StringBuilder();		// StringBuilder.append(text) is faster than concatenation (+ operator) of String...
		
		for (i = 0; i < ALPHA_NUMERICS.length; i++) {		// generating alphanumeric characters...
			if (i < 10) {
				ALPHA_NUMERICS[i] = (char) ('0' + i);		// 0 to 9...
			}
			else {
				ALPHA_NUMERICS[i] = (char) ('a' + i - 10);		// a to z...
			}
		}
		
		randomLength = RANDOM.nextInt(MAX_LENGTH) + 1;		// generating random length for our random string which is greater than 0 and less than or equal to 100...
		
		for (i = 0; i < randomLength; i++) {
			randomStringBuilder.append(ALPHA_NUMERICS[RANDOM.nextInt(ALPHA_NUMERICS.length)]);		// selecting a random character from ALPHA_NUMERICS array and appending it to the randomStringBuilder...
		}
		
		System.out.println(randomStringBuilder.toString());		// printing the random string we've generated...
	}
	
}